### ISSUE TITLE
Stuck in notebook

### ISSUE THREAD

**Issue by vibber** [epitaque/dreambooth_depth2img#3]
Hi there,
I am trying to run this locally on a windows machine. Getting stuck with the following. Can't really identify what the cause is:

Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]
Fetching 15 files: 100%|##########| 15/15 [00:00<00:00, 5057.03it/s]
Keyword arguments {'safety_checker': None} are not expected by StableDiffusionDepth2ImgPipeline and will be ignored.

Generating class images:   0%|          | 0/50 [00:00<?, ?it/s]
Generating class images:   0%|          | 0/50 [00:00<?, ?it/s]
+--------------------- Traceback (most recent call last) ---------------------+
| C:\Users\VERTIGO\dreamboothdepth\dreambooth_depth2img\train_dreambooth.py:8 |
| 34 in <module>                                                              |
|                                                                             |
|   831                                                                       |
|   832 if __name__ == "__main__":                                            |
|   833     args = parse_args()                                               |
| > 834     main(args)                                                        |
|   835                                                                       |
|                                                                             |
| C:\Users\VERTIGO\dreamboothdepth\dreambooth_depth2img\train_dreambooth.py:5 |
| 07 in main                                                                  |
|                                                                             |
|   504             for example in tqdm(                                      |
|   505                 sample_dataloader, desc="Generating class images", di |
|   506             ):                                                        |
| > 507                 images = pipeline(example["prompt"]).images           |
|   508                                                                       |
|   509                 for i, image in enumerate(images):                    |
|   510                     hash_image = hashlib.sha1(image.tobytes()).hexdig |
|                                                                             |
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\site-packages\torch\aut |
| ograd\grad_mode.py:27 in decorate_context                                   |
|                                                                             |
|    24         @functools.wraps(func)                                        |
|    25         def decorate_context(*args, **kwargs):                        |
|    26             with self.clone():                                        |
| >  27                 return func(*args, **kwargs)                          |
|    28         return cast(F, decorate_context)                              |
|    29                                                                       |
|    30     def _wrap_generator(self, func):                                  |
+-----------------------------------------------------------------------------+
TypeError: __call__() missing 1 required positional argument: 'image'
+--------------------- Traceback (most recent call last) ---------------------+
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\runpy.py:194 in         |
| _run_module_as_main                                                         |
|                                                                             |
|   191     main_globals = sys.modules["__main__"].__dict__                   |
|   192     if alter_argv:                                                    |
|   193         sys.argv[0] = mod_spec.origin                                 |
| > 194     return _run_code(code, main_globals, None,                        |
|   195                      "__main__", mod_spec)                            |
|   196                                                                       |
|   197 def run_module(mod_name, init_globals=None,                           |
|                                                                             |
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\runpy.py:87 in          |
| _run_code                                                                   |
|                                                                             |
|    84                        __loader__ = loader,                           |
|    85                        __package__ = pkg_name,                        |
|    86                        __spec__ = mod_spec)                           |
| >  87     exec(code, run_globals)                                           |
|    88     return run_globals                                                |
|    89                                                                       |
|    90 def _run_module_code(code, init_globals=None,                         |
|                                                                             |
| C:\Users\VERTIGO\anaconda3\envs\dreamboothdepth\Scripts\accelerate.exe\__ma |
| in__.py:7 in <module>                                                       |
|                                                                             |
| [Errno 2] No such file or directory:                                        |
| 'C:\\Users\\VERTIGO\\anaconda3\\envs\\dreamboothdepth\\Scripts\\accelerate. |
| exe\\__main__.py'                                                           |
|                                                                             |
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\site-packages\accelerat |
| e\commands\accelerate_cli.py:45 in main                                     |
|                                                                             |
|   42         exit(1)                                                        |
|   43                                                                        |
|   44     # Run                                                              |
| > 45     args.func(args)                                                    |
|   46                                                                        |
|   47                                                                        |
|   48 if __name__ == "__main__":                                             |
|                                                                             |
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\site-packages\accelerat |
| e\commands\launch.py:1104 in launch_command                                 |
|                                                                             |
|   1101     elif defaults is not None and defaults.compute_environment == Co |
|   1102         sagemaker_launcher(defaults, args)                           |
|   1103     else:                                                            |
| > 1104         simple_launcher(args)                                        |
|   1105                                                                      |
|   1106                                                                      |
|   1107 def main():                                                          |
|                                                                             |
| c:\users\vertigo\anaconda3\envs\dreamboothdepth\lib\site-packages\accelerat |
| e\commands\launch.py:567 in simple_launcher                                 |
|                                                                             |
|    564     process = subprocess.Popen(cmd, env=current_env)                 |
|    565     process.wait()                                                   |
|    566     if process.returncode != 0:                                      |
| >  567         raise subprocess.CalledProcessError(returncode=process.retur |
|    568                                                                      |
|    569                                                                      |
|    570 def multi_gpu_launcher(args):                                        |
+-----------------------------------------------------------------------------+
CalledProcessError: Command 
'['c:\\users\\vertigo\\anaconda3\\envs\\dreamboothdepth\\python.exe', 
'train_dreambooth.py', '--mixed_precision=fp16', 
'--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-depth', 
'--train_text_encoder', 
'--instance_data_dir=C:/Users/VERTIGO/Documents/my_concept', 
'--class_data_dir=C:/Users/VERTIGO\\Documents/classdata', 
'--output_dir=C:/Users/VERTIGO/dreambooth-concept', 
'--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a 
graphical illustration by oritoordream artist', '--class_prompt=a graphical 
illustration by an artist', '--resolution=512', '--train_batch_size=1', 
'--gradient_accumulation_steps=1', '--learning_rate=1e-6', 
'--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', 
'--max_train_steps=2000', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by vibber** [comment]
I ran the environment.yaml and I also installed from the instructions in diffusers/example/dreambooth readme

**Comment by epitaque** [comment]
The issue was it was trying to generate class images using the depth2img pipeline (which requires an image, as your error log indicates). I added an additional "--pretrained_txt2img_model_name_or_path" parameter which takes in a normal stable diffusion pipeline for generating class images.
